Repository wecode-bootcamp-korea/19-2nd-her-house-frontend, pull requests merged in 2021-05, with the labels that each got.

#4 [19기 김동현] Add : 서버와 통신확인, 수정사항 수정
  public/images/kakao_login_medium_narrow.png
  public/images/katok.jpg
  public/index.html
  src/Pages/Login/Login.js
  src/Pages/Signup/Component/SignupInput.js
  src/Pages/Signup/Signup.js
  src/Pages/Signup/useForm.js
  src/Pages/Signup/validate.js
  src/Routes.js
  src/config.js
  src/styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#6 [19기 김동현] Fix : 리뷰사항 반영, 프리티어 설정 변경
  .prettierrc
  package-lock.json
  package.json
  src/Pages/Login/Login.js
  src/Pages/Signup/Signup.js
Labels: Status: Accepted

#2 [19기 손주영] Complete : Category 페이지 완료, 공통 사항 수정.
  package.json
  src/Pages/category/components/CategoryContent/CategoryCarousel.js
  src/Pages/category/components/CategoryContent/CategoryFilter.js
  src/Pages/category/components/CategoryContent/CategoryLocation.js
  src/Pages/category/components/CategoryContent/ProductContent.js
  src/Pages/category/components/CategoryContent/index.js
  src/Pages/category/components/CategoryContent/mockData.js
  src/Pages/category/components/CategoryList/CategoryListItem.js
  src/Pages/category/components/CategoryList/index.js
  src/Pages/category/index.js
  src/Routes.js
  src/index.js
  src/styles/GlobalStyle.js
  yarn.lock
Labels: Status: 리뷰 요청

#5 [19기 김동현] Add : 일단 지도까진 띄워둠, Fix : 리뷰사항 반영
  package-lock.json
  package.json
  public/index.html
  src/Pages/Experts/Address.js
  src/Pages/Experts/Component/Modal.js
  src/Pages/Experts/Experts.js
  src/Pages/Experts/useChangePosition.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#3 [19기 채준형] Nav바 리뷰반영 및 리팩토링
  config.js
  package-lock.json
  package.json
  public/README.md
  public/data/categoryData.json
  public/images/logo.png
  src/Components/Footer/Footer.js
  src/Components/Nav/Nav.js
  src/Components/Nav/components/Category.js
  src/Components/Nav/components/CategoryList.js
  src/Components/Nav/components/NavAside.js
  src/Components/Nav/components/NavAsideIcon.js
  src/Components/Nav/components/NavMenuTab.js
  src/Components/Nav/navdata/NavMenuData.js
  src/Pages/Main/Main.js
  src/Routes.js
  src/index.js
  src/styles/GlobalStyle.js
Labels: Status: Accepted

#8 [19기 김동현] Add : 업체 List 추가
  package-lock.json
  public/data/companys.json
  src/Pages/Experts/Address.js
  src/Pages/Experts/Component/CompaniesList.js
  src/Pages/Experts/Component/CompanyCard.js
  src/Pages/Experts/Component/TextBox.js
  src/Pages/Experts/Experts.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#9 Add : 위치변경에 따른 지도 center 변경처리
  public/data/companys.json
  src/Pages/Experts/Component/CompanyCard.js
  src/Pages/Experts/Component/Distance.js
  src/Pages/Experts/Component/KakaoMap.js
  src/Pages/Experts/Component/Modal.js
  src/Pages/Experts/Component/TextBox.js
  src/Pages/Experts/Experts.js
  src/Pages/Main/Main.js
  src/Routes.js
  src/config.js
  src/index.js
Labels: Status: 리뷰 요청

#7 [19기 채준형]메인페이지(스토어) 메인슬라이드 및 특가/ 카데고리 + 인기상품(데이터 불러오는거까지)
  config.js
  package-lock.json
  package.json
  public/data/mainslideData.json
  public/data/productData.json
  public/images/realslide1.jpeg
  public/images/realslide2.jpeg
  public/images/realslide3.jpeg
  public/images/slide1.png
  public/images/slide2.png
  public/images/slide3.png
  public/images/slide5.png
  public/images/slideData2.jpeg
  src/Components/Nav/Nav.js
  src/Components/Nav/components/Category.js
  src/Components/Nav/components/CategoryList.js
  src/Components/Nav/components/CommunityTab.js
  src/Components/Nav/components/NavAside.js
  src/Components/Nav/components/SigongTab.js
  src/Components/Nav/components/StoreTab.js
  src/Components/Nav/navdata/CommunityTabData.js
  src/Components/Nav/navdata/SigongTabData.js
  src/Components/Nav/navdata/StoreTabData.js
  src/Components/up_scroll/UpScroll.js
  src/Pages/Main/Main.js
  src/Pages/Main/MainCategory.js
  src/Pages/Main/MainProduct.js
  src/Pages/Main/MainSlide.js
  src/Pages/Main/TodayDeal.js
  src/Pages/Main/components/HeadBanner.js
  src/Pages/Main/components/MainProductList.js
  src/Pages/Main/components/ProductFilter.js
  src/Pages/Main/components/ShipModal.js
  src/Pages/Main/components/SlideItem.js
  src/Pages/Main/components/VariousModal.js
  src/Routes.js
Labels: Status: 리뷰 요청

#11 [19기 김동현] Add : 페이징 처리 추가
  src/Pages/Experts/Component/CompanyCard.js
  src/Pages/Experts/Component/Distance.js
  src/Pages/Experts/Component/DistanceButton.js
  src/Pages/Experts/Component/KakaoMap.js
  src/Pages/Experts/Experts.js
  src/config.js
Labels: Status: 리뷰 요청
